#VERIFY_MSG = catOS/port:$(RELATIVE_PATH)***** making catOS port dir *****

subdir-$(CATOS_BOARD_STM32F103VET6_FIRE) += stm32f103vet6_fire
subdir-$(CATOS_BOARD_LINUX)				 += linux

include $(RULE_DIR)/rules.mk
