
# CINCLUDE_FILE += catOS/bsp/stm32f103vet6_fire/Libraries/CMSIS/Device/ST/STM32F1xx/Include
# CINCLUDE_FILE += catOS/bsp/interface

CINCLUDE_FILE += catOS/src/component/cat_stdio
CINCLUDE_FILE += catOS/src/component/cat_shell


subdir-y += exfuns
subdir-y += src

obj-y += test.o

include $(RULE_DIR)/rules.mk
